export const data = {
  headers: [
    { header: 'fullName', text: 'USER NAME' },
    { header: 'dateReceived', text: 'DATE RECEIVED' },
    { header: 'status', text: 'STATUS' },
    { header: 'driverMgr', text: 'DRIVER MANANGER' },
    { header: 'timeoff-view', text: 'View' },
    { header: 'sub-actions', text: 'Actions' },
  ],
  data: [
    {
      fullName: 'Bubba Gump',
      dateReceived: 'Jan 19 2021 • 8:30am',
      status: 'pending',
      driverMgr: 'DM99',
    },
    {
      fullName: 'Bubba Gump',
      dateReceived: 'Jan 19 2021 • 8:30am',
      status: 'approved',
      driverMgr: 'DM99',
    },
    {
      fullName: 'Bubba Gump',
      dateReceived: 'Jan 19 2021 • 8:30am',
      status: 'declined',
      driverMgr: 'DM99',
    },
    {
      fullName: 'Bubba Gump',
      dateReceived: 'Jan 19 2021 • 8:30am',
      status: 'pending',
      driverMgr: 'DM99',
    },
    {
      fullName: 'Bubba Gump',
      dateReceived: 'Jan 19 2021 • 8:30am',
      status: 'pending',
      driverMgr: 'DM99',
    },
    {
      fullName: 'Bubba Gump',
      dateReceived: 'Jan 19 2021 • 8:30am',
      status: 'pending',
      driverMgr: 'DM99',
    },
    {
      fullName: 'Bubba Gump',
      dateReceived: 'Jan 19 2021 • 8:30am',
      status: 'approved',
      driverMgr: 'DM99',
    },
    {
      fullName: 'Bubba Gump',
      dateReceived: 'Jan 19 2021 • 8:30am',
      status: 'declined',
      driverMgr: 'DM99',
    },
    {
      fullName: 'Bubba Gump',
      dateReceived: 'Jan 19 2021 • 8:30am',
      status: 'pending',
      driverMgr: 'DM99',
    },
    {
      fullName: 'Bubba Gump',
      dateReceived: 'Jan 19 2021 • 8:30am',
      status: 'pending',
      driverMgr: 'DM99',
    },
    {
      fullName: 'Bubba Gump',
      dateReceived: 'Jan 19 2021 • 8:30am',
      status: 'pending',
      driverMgr: 'DM99',
    },
    {
      fullName: 'Bubba Gump',
      dateReceived: 'Jan 19 2021 • 8:30am',
      status: 'approved',
      driverMgr: 'DM99',
    },
    {
      fullName: 'Bubba Gump',
      dateReceived: 'Jan 19 2021 • 8:30am',
      status: 'declined',
      driverMgr: 'DM99',
    },
    {
      fullName: 'Bubba Gump',
      dateReceived: 'Jan 19 2021 • 8:30am',
      status: 'pending',
      driverMgr: 'DM99',
    },
    {
      fullName: 'Bubba Gump',
      dateReceived: 'Jan 19 2021 • 8:30am',
      status: 'pending',
      driverMgr: 'DM99',
    },
  ],
};
