export const eventCodes = {
  BBT: 'Begin Bobtail',
  BMT: 'Begin Empty',
  CHK: 'Check Call',
  CTR: 'Change Trailer(s)',
  DLT: 'Drop Loaded Trailer',
  DMT: 'Drop Empty Trailer',
  DRL: 'Final Drop Loaded Trailer',
  DRVH: 'Driver Home',
  EBT: 'End Bobtail',
  EMT: 'End Empty',
  HLT: 'Hook Loaded Trailer',
  HMT: 'Hook Empty Trailer',
  HPL: 'Hook Preloaded Trailer',
  LLD: 'Live Load',
  LUL: 'Live Unload',
  RTP: 'Route Point',
  TRP: 'Hometime',
  XDL: 'Transfer Load',
  XDU: 'Transfer Unload',
};
